services:
  - type: web
    name: simulador-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn simulador.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: simulador.settings
      - key: PYTHON_VERSION
        value: 3.11